### ISSUE TITLE
Вид папки

### ISSUE THREAD

**Issue by osmanuss** [ChEDj/Progi#1]
[ReadMe.md](https://github.com/ChEDj/Progi/files/6869561/ReadMe.md)

Твой репозиторий должен в себя включать:
1) папка для практических
2) папка для лаб
3) файл ReadMe.md, где будет отображаться таблица с выполненными заданиями
---
.md - файлы типа markdown, это как html, только с добавлением многих фишек, которые упрощают верстку. Для гитхаба подходит идеально. Я тебе скинул в этом сообщении файл, который я использовал в течение семестра. Там ты найдешь таблицу. Тебе надо в свой readme файл засунуть такую же, только чтобы там были только те задания, которые ты выполнил. Чтобы я не путался
---
https://dillinger.io
вот онлайн .md редактор. Там ты сразу сможешь увидеть, что в итоге у тебя выйдет на сайте
---
Это твой репозиторий на гитхабе. Твой readme файл пустой, поэтому, когда люди заходят, они ничего не видят
![](https://user-images.githubusercontent.com/71592997/126801063-74b13c70-fb39-4819-91e3-f72934761019.png)
---
А это мой репозиторий. Гитхаб автоматически считывает файл readme и показывает его содержимое на главном экране репозитория
![](https://user-images.githubusercontent.com/71592997/126801244-c194a216-ac28-4d5f-bce1-748f06a1c6c7.png)
---

**Comment by osmanuss** [comment]
https://dillinger.io
вот онлайн редактор. Там ты сразу сможешь увидеть, что в итоге у тебя выйдет на сайте

**Comment by osmanuss** [comment]
![image](https://user-images.githubusercontent.com/71592997/126801063-74b13c70-fb39-4819-91e3-f72934761019.png)
Это твой репозиторий на гитхабе. Твой readme файл пустой, поэтому, когда люди заходят, они ничего не видят

**Comment by osmanuss** [comment]
![image](https://user-images.githubusercontent.com/71592997/126801244-c194a216-ac28-4d5f-bce1-748f06a1c6c7.png)
А это мой репозиторий. Гитхаб автоматически считывает файл readme и показывает его содержимое на главном экране репозитория

**Comment by ChEDj** [comment]
Исправлено

**Comment by osmanuss** [comment]
Ссылки не работают корректно

**Comment by ChEDj** [comment]
Все сделал
