### ISSUE TITLE
Оформление проекта С++

### ISSUE THREAD

**Issue by osmanuss** [ChEDj/Progi#2]
![image](https://user-images.githubusercontent.com/71592997/126803359-0f9cd105-be71-43ab-99dc-8a6f238729dc.png)
Советую хранить и решение и сам проект в одной папке. Так удобнее.

Можно один раз нажать и дальше галочка будет автоматически ставиться

**Comment by osmanuss** [comment]
можно один раз нажать и дальше галочка будет автоматически ставиться

**Comment by ChEDj** [comment]
Исправлено
