### ISSUE TITLE
ex1 С++ 

### ISSUE THREAD

**Issue by osmanuss** [ChEDj/Progi#5]
https://github.com/ChEDj/Progi/blob/c5c680db4295ed10514d460431e38aaa39c65178/Ex1/C%2B%2B/C%2B%2B/C%2B%2B.cpp#L4-L9
---
1) В 9 строке ты можешь написать просто `cout<<` без `std::` , так как ты в 4 строке написал `using namespace std`. Хз, может быть ты просто не заметил это
2) В 8 строке в кавычках можно написать просто `"rus"`

Так же советую использовать вместо `using-директивов` `using-объявления`
Подробнее: https://ravesli.com/urok-54-using-statements/

**Comment by ChEDj** [comment]
Исправлено
